apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: import-tests-go-mtmasyep-workflow
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: import-tests-go-mtmasyep-workflow 
  name: import-tests-go-mtmasyep-workflow
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: import-tests-go-mtmasyep-workflow
    weight: 100 
